import { Program, Subscription, AdminStats } from './types'

export const mockPrograms: Program[] = [
  // US - 4 programs
  {
    id: '1',
    name: 'Master of Science in Computer Science',
    school: 'MIT',
    country: 'US',
    degree: 'master',
    field: 'Computer Science',
    status: 'open',
    deadline: '2026-04-15',
    languageReq: 'TOEFL 100 / IELTS 7.0',
    gpaReq: 3.5,
    fee: 75,
    applyUrl: 'https://www.eecs.mit.edu/academics/graduate-programs/',
    description: 'A rigorous program designed for students who wish to develop advanced expertise in computer science theory, systems, and applications.',
    updatedAt: '2026-03-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'Master of Business Administration',
    school: 'Harvard University',
    country: 'US',
    degree: 'master',
    field: 'Business',
    status: 'closed',
    deadline: '2025-12-01',
    languageReq: 'TOEFL 109 / IELTS 7.5',
    gpaReq: 3.5,
    fee: 250,
    applyUrl: 'https://www.hbs.edu/mba/admissions/',
    description: 'Harvard Business School\'s MBA program develops leaders who make a difference in the world through case-based learning.',
    updatedAt: '2026-02-15T08:30:00Z',
  },
  {
    id: '3',
    name: 'PhD in Data Science',
    school: 'Stanford University',
    country: 'US',
    degree: 'phd',
    field: 'Data Science',
    status: 'open',
    deadline: '2026-04-01',
    languageReq: 'TOEFL 89 / IELTS 7.0',
    gpaReq: 3.7,
    fee: 125,
    applyUrl: 'https://datascience.stanford.edu/programs/phd',
    description: 'The Stanford Data Science PhD program trains researchers in statistical methodology, machine learning, and data-driven decision making.',
    updatedAt: '2026-03-05T12:00:00Z',
  },
  {
    id: '4',
    name: 'Bachelor of Science in Engineering',
    school: 'Carnegie Mellon University',
    country: 'US',
    degree: 'bachelor',
    field: 'Engineering',
    status: 'closed',
    deadline: '2026-01-01',
    languageReq: 'TOEFL 102 / IELTS 7.0',
    gpaReq: null,
    fee: 85,
    applyUrl: 'https://engineering.cmu.edu/admissions/',
    description: 'CMU\'s engineering program is known for its interdisciplinary approach and close ties to industry and research.',
    updatedAt: '2026-02-20T09:00:00Z',
  },

  // UK - 3 programs
  {
    id: '5',
    name: 'Master of Science in Artificial Intelligence',
    school: 'University of Oxford',
    country: 'UK',
    degree: 'master',
    field: 'Computer Science',
    status: 'open',
    deadline: '2026-04-30',
    languageReq: 'IELTS 7.5 / TOEFL 110',
    gpaReq: 3.5,
    fee: 75,
    applyUrl: 'https://www.ox.ac.uk/admissions/graduate/courses/msc-advanced-computer-science',
    description: 'Oxford\'s AI MSc program covers machine learning, natural language processing, computer vision, and the ethical implications of AI systems.',
    updatedAt: '2026-03-03T14:00:00Z',
  },
  {
    id: '6',
    name: 'PhD in Public Policy',
    school: 'University of Cambridge',
    country: 'UK',
    degree: 'phd',
    field: 'Public Policy',
    status: 'closed',
    deadline: '2025-11-15',
    languageReq: 'IELTS 7.0 / TOEFL 100',
    gpaReq: 3.8,
    fee: 60,
    applyUrl: 'https://www.polis.cam.ac.uk/graduate-study/phd',
    description: 'Cambridge\'s Public Policy PhD provides rigorous training in policy analysis, political economy, and evidence-based governance.',
    updatedAt: '2026-01-10T11:00:00Z',
  },
  {
    id: '7',
    name: 'Master of Science in Data Science',
    school: 'Imperial College London',
    country: 'UK',
    degree: 'master',
    field: 'Data Science',
    status: 'pending',
    deadline: null,
    languageReq: 'IELTS 6.5 / TOEFL 92',
    gpaReq: 3.3,
    fee: 100,
    applyUrl: 'https://www.imperial.ac.uk/computing/prospective-students/courses/pg/msc-data-science/',
    description: 'Imperial\'s Data Science MSc bridges the gap between statistical theory and real-world data engineering at scale.',
    updatedAt: '2026-02-28T16:30:00Z',
  },

  // AU - 2 programs
  {
    id: '8',
    name: 'Master of Engineering',
    school: 'University of Melbourne',
    country: 'AU',
    degree: 'master',
    field: 'Engineering',
    status: 'open',
    deadline: '2026-05-31',
    languageReq: 'IELTS 6.5 / TOEFL 79',
    gpaReq: 3.0,
    fee: 100,
    applyUrl: 'https://study.unimelb.edu.au/find/courses/graduate/master-of-engineering/',
    description: 'Melbourne\'s Master of Engineering offers specializations across civil, mechanical, electrical, and software engineering disciplines.',
    updatedAt: '2026-03-02T08:00:00Z',
  },
  {
    id: '9',
    name: 'PhD in Medicine',
    school: 'University of Sydney',
    country: 'AU',
    degree: 'phd',
    field: 'Medicine',
    status: 'closed',
    deadline: '2025-10-31',
    languageReq: 'IELTS 7.0 / TOEFL 94',
    gpaReq: 3.5,
    fee: 150,
    applyUrl: 'https://www.sydney.edu.au/medicine-health/study/research-degrees.html',
    description: 'The University of Sydney\'s PhD in Medicine prepares researchers for careers in biomedical research, clinical sciences, and public health.',
    updatedAt: '2026-01-20T10:30:00Z',
  },

  // CA - 2 programs
  {
    id: '10',
    name: 'Master of Science in Computer Science',
    school: 'University of Toronto',
    country: 'CA',
    degree: 'master',
    field: 'Computer Science',
    status: 'closed',
    deadline: '2025-12-15',
    languageReq: 'TOEFL 93 / IELTS 6.5',
    gpaReq: 3.3,
    fee: 125,
    applyUrl: 'https://web.cs.toronto.edu/graduate/prospective',
    description: 'U of T\'s CS MSc is among the world\'s top programs, with world-class research in AI, systems, theory, and human-computer interaction.',
    updatedAt: '2026-02-10T13:00:00Z',
  },
  {
    id: '11',
    name: 'Bachelor of Commerce',
    school: 'McGill University',
    country: 'CA',
    degree: 'bachelor',
    field: 'Business',
    status: 'pending',
    deadline: null,
    languageReq: 'TOEFL 90 / IELTS 6.5',
    gpaReq: null,
    fee: 115,
    applyUrl: 'https://www.mcgill.ca/desautels/programs/bcom',
    description: 'McGill\'s BCom program at the Desautels Faculty of Management provides a strong foundation in business with global perspective.',
    updatedAt: '2026-03-07T09:45:00Z',
  },

  // SG - 1 program
  {
    id: '12',
    name: 'PhD in Computer Science',
    school: 'National University of Singapore',
    country: 'SG',
    degree: 'phd',
    field: 'Computer Science',
    status: 'open',
    deadline: '2026-05-15',
    languageReq: 'TOEFL 85 / IELTS 6.0',
    gpaReq: 3.2,
    fee: 50,
    applyUrl: 'https://www.comp.nus.edu.sg/programmes/pg/phd/',
    description: 'NUS Computing\'s PhD program is Asia\'s top-ranked CS doctoral program, with strong industry partnerships and a vibrant research community.',
    updatedAt: '2026-03-08T07:00:00Z',
  },
]

export const mockStats: AdminStats = {
  totalPrograms: 200,
  openPrograms: 87,
  totalSubscribers: 1432,
  verifiedSubscribers: 1185,
  todayNotifications: 34,
  monthNotifications: 512,
}

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub-1',
    email: 'alice@example.com',
    degrees: ['master', 'phd'],
    fields: ['Computer Science', 'Data Science'],
    countries: ['US', 'UK', 'CA'],
    verified: true,
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'sub-2',
    email: 'bob@example.com',
    degrees: ['master'],
    fields: ['Business'],
    countries: ['US', 'UK'],
    verified: true,
    createdAt: '2026-02-14T14:30:00Z',
  },
  {
    id: 'sub-3',
    email: 'carol@example.com',
    degrees: ['phd'],
    fields: ['Engineering', 'Computer Science'],
    countries: ['AU', 'SG'],
    verified: false,
    createdAt: '2026-03-05T11:15:00Z',
  },
]
